src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("posts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete
from django.contrib.auth.decorators import login_required

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name = "home"),
    path('create/', login_required(BlogPostCreate.as_view()), name = "create"),  
    path('detail/<str:slug>/', BlogPostDetail.as_view(), name = "detail"),
    path('edit/<str:slug>/', login_required(BlogPostEdit.as_view()), name = "edit"),               
    path('delete/<str:slug>/', login_required(BlogPostDelete.as_view()), name = "delete"),       
]

src/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse


User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.CharField(max_length=255, unique=True, blank=True)
    Author = models.ForeignKey(User, on_delete= models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank = True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True,null=True, upload_to='blog/')
    
    class Meta:
        ordering = ['-last_updated']
        verbose_name = 'Article'
        
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)       
        super().save(*args, **kwargs)
    
    @property
    def author_or_self_default(self):
        return self.Author.username if self.Author else "l'Auteur inconnue"
    
    def get_absolute_url(self):
        return reverse("posts:home")
    

src/posts/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from posts.models import BlogPost
from django.urls import reverse_lazy


class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"
    template_name = "posts/blog_home.html"   
    
    def get_queryset(self): # méthode appeler par ListView our récuperer les datas. On l'a surchage pour filtrer l'affichage en fonction de l'utilisateur
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published = True)
    
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blog_create.html"
    fields = ["title", "content"]
    
class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = "posts/blog_edit.html"
    fields = ['title','content','published',]
    
class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"
    template_name = "posts/blog_details.html"
    
class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('posts:home')
    template_name = "posts/blog_confirm_delete.html"
    context_object_name = "article"

src/posts/templates/posts/blog_confirm_delete.html
{% extends "base.html"%}

{% block title%}
    <title>Supprimer un article</title>
{% endblock %}


{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Etes vous sur de vouloir supprimer "{{article}}"?</p>
        <input type = "submit" value="Oui, supprimer" class="btn-delete">
    </form>

{% endblock %}

src/posts/templates/posts/blog_create.html
{% extends "base.html"%}

{% block title%}
    <title>Ajouter un article</title>
{% endblock %}

{% block content %}

    <h1>Ajouter un article</h1>

    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type = "submit" value="Créer" class="btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blog_details.html
{% extends "base.html"%}

{% block title%}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}

    <article class="post-detail">
        <h1>{{ post.title }}<h1>
        <img src="{{ post.thumbnail.url }}" alt="IMAGE DE L'ARTICLE">
        <div>{{ post.content|linebreaks|safe }}</div>    
    </article>

{% endblock %}

src/posts/templates/posts/blog_edit.html
{% extends "base.html"%}

{% block title%}
    <title>Editer un article</title>
{% endblock %}

{% block content %}

    <h1>Editer un article</h1>

    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type = "submit" value="Editer" class="btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blog_home.html
{% extends "base.html"%}

{% block title%}
    <title>Accueil du site</title>
{% endblock %}

{% block content %}

    <h1>Le blog de Limare</h1>
    {% for post in posts %}
        <article> 

            <div class="post-title">
                <h2>{{ post.title }}</h2>

                {% if request.user.is_authenticated %}
                <div>
                    <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                    <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                </div>
                {% endif %}
            </div>

            <h5 class="post-author">Publié par <i>{{ post.author_or_self_default }}</i> le {{ post.created_on|date:'j F Y'}}</h5>
            <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>   

            <form action="{% url 'posts:detail' slug=post.slug %}">
                <button class="btn-submit">Lire l'article</button>
            </form>

        </article>

    {% endfor%}

{% endblock%}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
    
<nav>
<a href="{% url 'posts:home' %}">Accueil</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:create' %}">Ajouter un article</a>
    {% endif %}
</nav>

<body>
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>   
</body>
</html>